Done event screen correct
Culturale/culturale-frontend pull request #38
Opened 2023-05-13 16:16 UTC by ElsaBoix

La screen del evento esta correct

2023-05-14 10:56 UTC, quimvi requested changes

2023-05-14 10:56 UTC, quimvi commented on app/views/home-screen/home-screen.tsx
> +type HomeNavigation = StackNavigationProp<RootParamList, 'EventScreen'>;
```suggestion
type HomeNavigation = StackNavigationProp<RootParamList, 'HomeScreen'>;
```

2023-05-14 10:56 UTC, quimvi commented on app/views/home-screen/home-screen.tsx
> +    };
Esta funcion se tendria que ponser fuera del render item

2023-05-14 10:56 UTC, quimvi commented on app/views/EventsScreen.tsx
Por que hay 2 event secreen? Esta se tiene que borrar ?

2023-05-15 12:41 UTC, ElsaBoix commented on app/views/home-screen/home-screen.tsx
> +    };
No puede ir fuera del render item, necesito el item bro

2023-05-15 12:51 UTC, quimvinals approved these changes

2023-05-15 12:54 UTC, merged