Calendar my events
Culturale/culturale-frontend pull request #42
Opened 2023-05-16 16:02 UTC by ElsaBoix

2023-05-18 16:48 UTC, quimvi requested changes

2023-05-18 16:48 UTC, quimvi commented on app/application/controllers/event-controller/event-controller.ts
> +    eventToBeMod.updateParticipant(user);
```suggestion
    event.updateParticipant(user);
```

2023-05-18 16:48 UTC, quimvi commented on app/infrastructure/api/api.ts
> +    await this.post<MessageDocument>('/events/newParticipant', {
Por que es MEssageDocument ??

2023-05-18 16:48 UTC, quimvi commented on app/views/event-screen/event-screen.props.ts
> +}
Esto no va aqui si no a las props de navegacion.

2023-05-18 16:51 UTC, ElsaBoix commented on app/infrastructure/api/api.ts
> +    await this.post<MessageDocument>('/events/newParticipant', {
porque retorna participante añadido correctamente

2023-05-20 16:28 UTC, quimvi approved these changes

2023-05-20 16:31 UTC, merged